site_name: SWE303 - Software Project Management
site_url: https://norbutlepcha25.github.io/SWE303

use_directory_urls: false

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.copy
    - content.tooltips
    - navigation.expand
    # - navigation.footer
    - content.action.edit
    - content.action.view

  language: en
  palette:
    - scheme: default
      primary: black
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      accent: blue
      primary: blue grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  font:
    text: Roboto
    code: Source Code Pro
  icon:
    logo: material/code-json

extra_css:
  - stylesheets/color.css
  - stylesheets/print.css
  - https://unpkg.com/katex@0/dist/katex.min.css

copyright: |
  &copy; 2025 <a href="https://github.com/norbutlepcha25" target="_blank" rel="noopener">Norbu Tshering Lepcha</a>

extra:
  generator: false
  base_url: /SWE303

markdown_extensions:
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      preserve_tabs: true
      custom_fences:
        - name: mermaid
          class: mermaid
  - admonition
  - pymdownx.details
  - abbr
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.tilde
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

plugins:
  - search
  - glightbox
  - macros:
      module_name: main
      include_dir: macros
      include_yaml:
        - macros/vars.yml
        - macros/glossary.yml
        - macros/learning_outcomes.yml

  - minify:
      minify_html: true

nav:
  - Home: index.md

  - Unit 1:
      - Overview: unit1/overview.md
      - 1.1 Fundamentals of Project Management: unit1/topic1.md
      - 1.2 Software Development Life Cycle Models: unit1/topic2.md
      - 1.3 Project management methodologies: unit1/topic3.md
      # - Summary: unit1/summary.md

  - Unit 2:
      - Overview: unit2/overview.md
      - 2.1 Project initiation: unit2/topic1.md
      - 2.2 Requirements gathering processes: unit2/topic2.md
      - 2.3 Scope definition and management: unit2/topic3.md
  #     - Summary: unit2/summary.md

  - Unit 3:
      - Overview: unit3/overview.md
      - 3.1 Time management: unit3/topic1.md
      - 3.2 Cost management: unit3/topic2.md
      - 3.3 Resource management: unit3/topic3.md
      - 3.4 Communications management: unit3/topic4.md
  # - Summary: unit3/summary.md

  - "Unit 4": unit4.md
  - "Unit 5": unit5.md
  - "Unit 6": unit6.md

  # - Unit 7:
  #     - Overview: unit7/overview.md
  #     - 7.1 Project closure activities: unit7/topic1.md
  #     - 7.2 Post-project evaluation: unit7/topic2.md
  #     - 7.3 Project archives and knowledge management: unit7/topic3.md
  #     - Summary: unit7/summary.md
  # - Glossary: glossary.md
